FROM alpine:3.23 AS build

ARG TARGETARCH

RUN apk add --no-cache build-base make curl musl-dev

WORKDIR /envhttpd/

COPY . /envhttpd/

RUN make -f src/Makefile bin/envhttpd-static

FROM scratch
COPY --from=build /envhttpd/bin/envhttpd-static /envhttpd-static
