image: kilna/envhttpd
description: HTTP Server for Environment Variables
platforms:
  - linux/amd64
  - linux/386
  - linux/arm64
  - linux/arm/v6
  - linux/arm/v7
  - linux/riscv64
  - linux/s390x
  - linux/ppc64le
