name: Build and deploy all architectures to DockerHub
on:
  release:
    type:
      - published
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare
        run: |
          TAG=${{ github.event.release.tag_name }}
          echo "VERSION_TAG=${TAG#v}" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Docker meta
        uses: docker/metadata-action@v5
        id: meta
        with:
          images: ${{ env.REGISTRY_IMAGE }}
          tags: |
            type=semver,pattern={{ version }}
            type=raw,value=latest
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: build
        uses: docker/build-push-action@v5
        with:
          context: .
          #platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/riskv64
          platforms: linux/amd64,linux/arm64
          push: true
          labels: |
            org.opencontainers.image.created:${{ github.event.release.created_at }}
            org.opencontainers.image.revision:${{ github.sha }}
            org.opencontainers.image.version:${{ github.event.release.tag_name }}
          tags: ${{ steps.meta.outputs.tags }}

